### ISSUE TITLE
为什么使用 marmot 加无法访问 Google 翻译的链接？ 

### ISSUE THREAD

**Issue by e9571** [hunterhug/GoSpider#11]
访问的链接如下：

https://translate.google.cn/translate_a/single?client=webapp&sl=zh-CN&tl=zh-CN&hl=zh-CN&dt=at,bd,ex,ld,md,qca,rw,rm,sos,ss,t&ssel=0&tsel=3&kc=0&tk=470992.123882&q=This is an English sentence

Google 返回

Your client has issued a malformed or illegal request. That’s all we know

**Comment by hunterhug** [comment]
> 访问的链接如下：
> 
> https://translate.google.cn/translate_a/single?client=webapp&sl=zh-CN&tl=zh-CN&hl=zh-CN&dt=at,bd,ex,ld,md,qca,rw,rm,sos,ss,t&ssel=0&tsel=3&kc=0&tk=470992.123882&q=This is an English sentence
> 
> Google 返回
> 
> Your client has issued a malformed or illegal request. That’s all we know

使用姿势的问题，这个库仅仅是在http官方库包装了一层。请提供你的代码，才能知道什么问题
